

/*********************************************************************
 * version  Date        Name            Description
 * =================================================================
 * v1.0     8.17        Developer1      Add Method Implemented
 * 
 * 
 *******************************************************************/

public with sharing class Calculator {
    public Calculator() {

        
    }
    
    public integer add(integer a, integer b) {
                return a+b;
            }
           
    
}