
/*********************************************************************
 * version  Date        Name            Description
 * =================================================================
 * v1.0     8.17        Developer1      Add Method Implemented
 * v2.0     8.17        Developer2      sub method implemented
 * 
 *******************************************************************/


public with sharing class Calculator {
    public Calculator() {

        
    }

   
public integer sub(integer a, integer b) {
    return a-b;
}
        

    
    public integer add(integer a, integer b) {
                return a+b;
            }
           
    
}